package com.guide.ssm.module.user.pojo;

import java.util.Date;

public class TbAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.Aid
     *
     * @mbggenerated
     */
    private String aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.Account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.Password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.Email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.Privilege
     *
     * @mbggenerated
     */
    private String privilege;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.Arid
     *
     * @mbggenerated
     */
    private String arid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.Sid
     *
     * @mbggenerated
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.Del
     *
     * @mbggenerated
     */
    private String del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.ChangeTime
     *
     * @mbggenerated
     */
    private Date changetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.DelTime
     *
     * @mbggenerated
     */
    private Date deltime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    public TbAdmin(String aid, String account, String password, String email, String privilege, String arid, String sid, String del, Date createtime, Date changetime, Date deltime) {
        this.aid = aid;
        this.account = account;
        this.password = password;
        this.email = email;
        this.privilege = privilege;
        this.arid = arid;
        this.sid = sid;
        this.del = del;
        this.createtime = createtime;
        this.changetime = changetime;
        this.deltime = deltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.Aid
     *
     * @return the value of tb_admin.Aid
     *
     * @mbggenerated
     */
    public String getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.Account
     *
     * @return the value of tb_admin.Account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.Password
     *
     * @return the value of tb_admin.Password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.Email
     *
     * @return the value of tb_admin.Email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.Privilege
     *
     * @return the value of tb_admin.Privilege
     *
     * @mbggenerated
     */
    public String getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.Arid
     *
     * @return the value of tb_admin.Arid
     *
     * @mbggenerated
     */
    public String getArid() {
        return arid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.Sid
     *
     * @return the value of tb_admin.Sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.Del
     *
     * @return the value of tb_admin.Del
     *
     * @mbggenerated
     */
    public String getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.CreateTime
     *
     * @return the value of tb_admin.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.ChangeTime
     *
     * @return the value of tb_admin.ChangeTime
     *
     * @mbggenerated
     */
    public Date getChangetime() {
        return changetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.DelTime
     *
     * @return the value of tb_admin.DelTime
     *
     * @mbggenerated
     */
    public Date getDeltime() {
        return deltime;
    }
}