package com.guide.ssm.module.user.pojo;

import java.util.Date;

public class TbAdvice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advice.ADid
     *
     * @mbggenerated
     */
    private String adid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advice.Title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advice.Advice
     *
     * @mbggenerated
     */
    private String advice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advice.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advice.Atime
     *
     * @mbggenerated
     */
    private Date atime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advice.Status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advice.Vid
     *
     * @mbggenerated
     */
    private String vid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advice
     *
     * @mbggenerated
     */
    public TbAdvice(String adid, String title, String advice, String type, Date atime, String status, String vid) {
        this.adid = adid;
        this.title = title;
        this.advice = advice;
        this.type = type;
        this.atime = atime;
        this.status = status;
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advice.ADid
     *
     * @return the value of tb_advice.ADid
     *
     * @mbggenerated
     */
    public String getAdid() {
        return adid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advice.Title
     *
     * @return the value of tb_advice.Title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advice.Advice
     *
     * @return the value of tb_advice.Advice
     *
     * @mbggenerated
     */
    public String getAdvice() {
        return advice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advice.type
     *
     * @return the value of tb_advice.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advice.Atime
     *
     * @return the value of tb_advice.Atime
     *
     * @mbggenerated
     */
    public Date getAtime() {
        return atime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advice.Status
     *
     * @return the value of tb_advice.Status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advice.Vid
     *
     * @return the value of tb_advice.Vid
     *
     * @mbggenerated
     */
    public String getVid() {
        return vid;
    }
}