package com.guide.ssm.module.user.pojo;

public class TbAdminAdvice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_advice.ADid
     *
     * @mbggenerated
     */
    private String adid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_advice.Aid
     *
     * @mbggenerated
     */
    private String aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_advice.Status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_advice
     *
     * @mbggenerated
     */
    public TbAdminAdvice(String adid, String aid, String status) {
        this.adid = adid;
        this.aid = aid;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin_advice.ADid
     *
     * @return the value of tb_admin_advice.ADid
     *
     * @mbggenerated
     */
    public String getAdid() {
        return adid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin_advice.Aid
     *
     * @return the value of tb_admin_advice.Aid
     *
     * @mbggenerated
     */
    public String getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin_advice.Status
     *
     * @return the value of tb_admin_advice.Status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }
}