package com.guide.ssm.module.user.pojo;

public class TbArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.Arid
     *
     * @mbggenerated
     */
    private String arid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.Area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.Longitude
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.Latitude
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.Radius
     *
     * @mbggenerated
     */
    private Integer radius;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.Description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.Cid
     *
     * @mbggenerated
     */
    private String cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area
     *
     * @mbggenerated
     */
    public TbArea(String arid, String area, String longitude, String latitude, Integer radius, String description, String cid) {
        this.arid = arid;
        this.area = area;
        this.longitude = longitude;
        this.latitude = latitude;
        this.radius = radius;
        this.description = description;
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.Arid
     *
     * @return the value of tb_area.Arid
     *
     * @mbggenerated
     */
    public String getArid() {
        return arid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.Area
     *
     * @return the value of tb_area.Area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.Longitude
     *
     * @return the value of tb_area.Longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.Latitude
     *
     * @return the value of tb_area.Latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.Radius
     *
     * @return the value of tb_area.Radius
     *
     * @mbggenerated
     */
    public Integer getRadius() {
        return radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.Description
     *
     * @return the value of tb_area.Description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.Cid
     *
     * @return the value of tb_area.Cid
     *
     * @mbggenerated
     */
    public String getCid() {
        return cid;
    }
}