package com.guide.ssm.module.user.pojo;

import java.util.Date;

public class TbLocation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_location.Lid
     *
     * @mbggenerated
     */
    private String lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_location.Vid
     *
     * @mbggenerated
     */
    private String vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_location.Sid
     *
     * @mbggenerated
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_location.Time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    public TbLocation(String lid, String vid, String sid, Date time) {
        this.lid = lid;
        this.vid = vid;
        this.sid = sid;
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_location.Lid
     *
     * @return the value of tb_location.Lid
     *
     * @mbggenerated
     */
    public String getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_location.Vid
     *
     * @return the value of tb_location.Vid
     *
     * @mbggenerated
     */
    public String getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_location.Sid
     *
     * @return the value of tb_location.Sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_location.Time
     *
     * @return the value of tb_location.Time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }
}