package com.guide.ssm.module.user.pojo;

public class TbProvince {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_province.Pid
     *
     * @mbggenerated
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_province.Province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated
     */
    public TbProvince(String pid, String province) {
        this.pid = pid;
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_province.Pid
     *
     * @return the value of tb_province.Pid
     *
     * @mbggenerated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_province.Province
     *
     * @return the value of tb_province.Province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }
}