package com.guide.ssm.module.user.pojo;

public class TbSpot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_spot.Sid
     *
     * @mbggenerated
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_spot.Spot
     *
     * @mbggenerated
     */
    private String spot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_spot.Longitude
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_spot.Latitude
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_spot.Radius
     *
     * @mbggenerated
     */
    private Integer radius;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_spot.Arid
     *
     * @mbggenerated
     */
    private String arid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_spot.Description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_spot.Voice
     *
     * @mbggenerated
     */
    private String voice;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spot
     *
     * @mbggenerated
     */
    public TbSpot(String sid, String spot, String longitude, String latitude, Integer radius, String arid, String description, String voice) {
        this.sid = sid;
        this.spot = spot;
        this.longitude = longitude;
        this.latitude = latitude;
        this.radius = radius;
        this.arid = arid;
        this.description = description;
        this.voice = voice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spot.Sid
     *
     * @return the value of tb_spot.Sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spot.Spot
     *
     * @return the value of tb_spot.Spot
     *
     * @mbggenerated
     */
    public String getSpot() {
        return spot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spot.Longitude
     *
     * @return the value of tb_spot.Longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spot.Latitude
     *
     * @return the value of tb_spot.Latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spot.Radius
     *
     * @return the value of tb_spot.Radius
     *
     * @mbggenerated
     */
    public Integer getRadius() {
        return radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spot.Arid
     *
     * @return the value of tb_spot.Arid
     *
     * @mbggenerated
     */
    public String getArid() {
        return arid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spot.Description
     *
     * @return the value of tb_spot.Description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spot.Voice
     *
     * @return the value of tb_spot.Voice
     *
     * @mbggenerated
     */
    public String getVoice() {
        return voice;
    }
}