package com.guide.ssm.module.user.mapper;

import com.guide.ssm.module.user.pojo.SysUser;
import com.guide.ssm.module.user.pojo.SysUserExample;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int countByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int deleteByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Delete({
        "delete from sys_user",
        "where sys_user_id = #{sysUserId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long sysUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Insert({
        "insert into sys_user (sys_user_id, sys_user_login_name, ",
        "sys_user_login_password, sys_user_status, ",
        "sys_user_is_delete, sys_user_register_datetime, ",
        "sys_user_register_source, sys_user_type, ",
        "sys_user_sex, sys_user_is_email_active, ",
        "sys_user_is_mobile_active, sys_user_register_type, ",
        "sys_user_pay_passwrod, sys_user_icon, ",
        "sys_user_real_name, sys_user_email, ",
        "sys_user_mobile, sys_user_weibo_id, ",
        "sys_user_qq_id)",
        "values (#{sysUserId,jdbcType=BIGINT}, #{sysUserLoginName,jdbcType=VARCHAR}, ",
        "#{sysUserLoginPassword,jdbcType=VARCHAR}, #{sysUserStatus,jdbcType=VARCHAR}, ",
        "#{sysUserIsDelete,jdbcType=VARCHAR}, #{sysUserRegisterDatetime,jdbcType=TIMESTAMP}, ",
        "#{sysUserRegisterSource,jdbcType=VARCHAR}, #{sysUserType,jdbcType=VARCHAR}, ",
        "#{sysUserSex,jdbcType=VARCHAR}, #{sysUserIsEmailActive,jdbcType=VARCHAR}, ",
        "#{sysUserIsMobileActive,jdbcType=VARCHAR}, #{sysUserRegisterType,jdbcType=VARCHAR}, ",
        "#{sysUserPayPasswrod,jdbcType=VARCHAR}, #{sysUserIcon,jdbcType=VARCHAR}, ",
        "#{sysUserRealName,jdbcType=VARCHAR}, #{sysUserEmail,jdbcType=VARCHAR}, ",
        "#{sysUserMobile,jdbcType=VARCHAR}, #{sysUserWeiboId,jdbcType=VARCHAR}, ",
        "#{sysUserQqId,jdbcType=VARCHAR})"
    })
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    List<SysUser> selectByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "sys_user_id, sys_user_login_name, sys_user_login_password, sys_user_status, ",
        "sys_user_is_delete, sys_user_register_datetime, sys_user_register_source, sys_user_type, ",
        "sys_user_sex, sys_user_is_email_active, sys_user_is_mobile_active, sys_user_register_type, ",
        "sys_user_pay_passwrod, sys_user_icon, sys_user_real_name, sys_user_email, sys_user_mobile, ",
        "sys_user_weibo_id, sys_user_qq_id",
        "from sys_user",
        "where sys_user_id = #{sysUserId,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    SysUser selectByPrimaryKey(Long sysUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysUser record, @Param("example") SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysUser record, @Param("example") SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Update({
        "update sys_user",
        "set sys_user_login_name = #{sysUserLoginName,jdbcType=VARCHAR},",
          "sys_user_login_password = #{sysUserLoginPassword,jdbcType=VARCHAR},",
          "sys_user_status = #{sysUserStatus,jdbcType=VARCHAR},",
          "sys_user_is_delete = #{sysUserIsDelete,jdbcType=VARCHAR},",
          "sys_user_register_datetime = #{sysUserRegisterDatetime,jdbcType=TIMESTAMP},",
          "sys_user_register_source = #{sysUserRegisterSource,jdbcType=VARCHAR},",
          "sys_user_type = #{sysUserType,jdbcType=VARCHAR},",
          "sys_user_sex = #{sysUserSex,jdbcType=VARCHAR},",
          "sys_user_is_email_active = #{sysUserIsEmailActive,jdbcType=VARCHAR},",
          "sys_user_is_mobile_active = #{sysUserIsMobileActive,jdbcType=VARCHAR},",
          "sys_user_register_type = #{sysUserRegisterType,jdbcType=VARCHAR},",
          "sys_user_pay_passwrod = #{sysUserPayPasswrod,jdbcType=VARCHAR},",
          "sys_user_icon = #{sysUserIcon,jdbcType=VARCHAR},",
          "sys_user_real_name = #{sysUserRealName,jdbcType=VARCHAR},",
          "sys_user_email = #{sysUserEmail,jdbcType=VARCHAR},",
          "sys_user_mobile = #{sysUserMobile,jdbcType=VARCHAR},",
          "sys_user_weibo_id = #{sysUserWeiboId,jdbcType=VARCHAR},",
          "sys_user_qq_id = #{sysUserQqId,jdbcType=VARCHAR}",
        "where sys_user_id = #{sysUserId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SysUser record);
}