package com.guide.ssm.module.user.mapper;

import com.guide.ssm.module.user.pojo.TbAdmin;
import java.util.List;

public interface TbAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    int insert(TbAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    TbAdmin selectByPrimaryKey(String aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    List<TbAdmin> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbAdmin record);
}