package com.guide.ssm.module.user.mapper;

import com.guide.ssm.module.user.pojo.TbAdminAdvice;
import java.util.List;

public interface TbAdminAdviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_advice
     *
     * @mbggenerated
     */
    int insert(TbAdminAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_advice
     *
     * @mbggenerated
     */
    List<TbAdminAdvice> selectAll();
}