package com.guide.ssm.module.user.mapper;

import com.guide.ssm.module.user.pojo.TbAdmin;
import com.guide.ssm.module.user.pojo.TbAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TbAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    int countByExample(TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    int deleteByExample(TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    @Delete({
        "delete from tb_admin",
        "where Aid = #{aid,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_admin (Aid, Account, ",
        "Password, Email, ",
        "Privilege, Arid, Sid, ",
        "Del, CreateTime, ",
        "ChangeTime, DelTime)",
        "values (#{aid,jdbcType=CHAR}, #{account,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{privilege,jdbcType=CHAR}, #{arid,jdbcType=CHAR}, #{sid,jdbcType=CHAR}, ",
        "#{del,jdbcType=CHAR}, #{createtime,jdbcType=TIMESTAMP}, ",
        "#{changetime,jdbcType=TIMESTAMP}, #{deltime,jdbcType=TIMESTAMP})"
    })
    int insert(TbAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    int insertSelective(TbAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    List<TbAdmin> selectByExample(TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "Aid, Account, Password, Email, Privilege, Arid, Sid, Del, CreateTime, ChangeTime, ",
        "DelTime",
        "from tb_admin",
        "where Aid = #{aid,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    TbAdmin selectByPrimaryKey(String aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbAdmin record, @Param("example") TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbAdmin record, @Param("example") TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    @Update({
        "update tb_admin",
        "set Account = #{account,jdbcType=VARCHAR},",
          "Password = #{password,jdbcType=VARCHAR},",
          "Email = #{email,jdbcType=VARCHAR},",
          "Privilege = #{privilege,jdbcType=CHAR},",
          "Arid = #{arid,jdbcType=CHAR},",
          "Sid = #{sid,jdbcType=CHAR},",
          "Del = #{del,jdbcType=CHAR},",
          "CreateTime = #{createtime,jdbcType=TIMESTAMP},",
          "ChangeTime = #{changetime,jdbcType=TIMESTAMP},",
          "DelTime = #{deltime,jdbcType=TIMESTAMP}",
        "where Aid = #{aid,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(TbAdmin record);
}