package com.guide.ssm.module.user.mapper;

import com.guide.ssm.module.user.pojo.TbAdminAdvice;
import com.guide.ssm.module.user.pojo.TbAdminAdviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface TbAdminAdviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_advice
     *
     * @mbggenerated
     */
    int countByExample(TbAdminAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_advice
     *
     * @mbggenerated
     */
    int deleteByExample(TbAdminAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_advice
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_admin_advice (ADid, Aid, Status)",
        "values (#{adid,jdbcType=CHAR}, #{aid,jdbcType=CHAR}, #{status,jdbcType=VARCHAR})"
    })
    int insert(TbAdminAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_advice
     *
     * @mbggenerated
     */
    int insertSelective(TbAdminAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_advice
     *
     * @mbggenerated
     */
    List<TbAdminAdvice> selectByExample(TbAdminAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_advice
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbAdminAdvice record, @Param("example") TbAdminAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_advice
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbAdminAdvice record, @Param("example") TbAdminAdviceExample example);
}