package com.guide.ssm.module.user.mapper;

import com.guide.ssm.module.user.pojo.TbAdvice;
import com.guide.ssm.module.user.pojo.TbAdviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TbAdviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advice
     *
     * @mbggenerated
     */
    int countByExample(TbAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advice
     *
     * @mbggenerated
     */
    int deleteByExample(TbAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advice
     *
     * @mbggenerated
     */
    @Delete({
        "delete from tb_advice",
        "where ADid = #{adid,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String adid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advice
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_advice (ADid, Title, ",
        "Advice, type, Atime, ",
        "Status, Vid)",
        "values (#{adid,jdbcType=CHAR}, #{title,jdbcType=VARCHAR}, ",
        "#{advice,jdbcType=VARCHAR}, #{type,jdbcType=CHAR}, #{atime,jdbcType=TIMESTAMP}, ",
        "#{status,jdbcType=CHAR}, #{vid,jdbcType=CHAR})"
    })
    int insert(TbAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advice
     *
     * @mbggenerated
     */
    int insertSelective(TbAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advice
     *
     * @mbggenerated
     */
    List<TbAdvice> selectByExample(TbAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advice
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ADid, Title, Advice, type, Atime, Status, Vid",
        "from tb_advice",
        "where ADid = #{adid,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    TbAdvice selectByPrimaryKey(String adid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advice
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbAdvice record, @Param("example") TbAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advice
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbAdvice record, @Param("example") TbAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advice
     *
     * @mbggenerated
     */
    @Update({
        "update tb_advice",
        "set Title = #{title,jdbcType=VARCHAR},",
          "Advice = #{advice,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=CHAR},",
          "Atime = #{atime,jdbcType=TIMESTAMP},",
          "Status = #{status,jdbcType=CHAR},",
          "Vid = #{vid,jdbcType=CHAR}",
        "where ADid = #{adid,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(TbAdvice record);
}