package com.guide.ssm.module.user.mapper;

import com.guide.ssm.module.user.pojo.TbArea;
import com.guide.ssm.module.user.pojo.TbAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TbAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area
     *
     * @mbggenerated
     */
    int countByExample(TbAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area
     *
     * @mbggenerated
     */
    int deleteByExample(TbAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area
     *
     * @mbggenerated
     */
    @Delete({
        "delete from tb_area",
        "where Arid = #{arid,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String arid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_area (Arid, Area, ",
        "Longitude, Latitude, Radius, ",
        "Description, Cid)",
        "values (#{arid,jdbcType=CHAR}, #{area,jdbcType=VARCHAR}, ",
        "#{longitude,jdbcType=CHAR}, #{latitude,jdbcType=CHAR}, #{radius,jdbcType=INTEGER}, ",
        "#{description,jdbcType=VARCHAR}, #{cid,jdbcType=CHAR})"
    })
    int insert(TbArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area
     *
     * @mbggenerated
     */
    int insertSelective(TbArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area
     *
     * @mbggenerated
     */
    List<TbArea> selectByExample(TbAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "Arid, Area, Longitude, Latitude, Radius, Description, Cid",
        "from tb_area",
        "where Arid = #{arid,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    TbArea selectByPrimaryKey(String arid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbArea record, @Param("example") TbAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbArea record, @Param("example") TbAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area
     *
     * @mbggenerated
     */
    @Update({
        "update tb_area",
        "set Area = #{area,jdbcType=VARCHAR},",
          "Longitude = #{longitude,jdbcType=CHAR},",
          "Latitude = #{latitude,jdbcType=CHAR},",
          "Radius = #{radius,jdbcType=INTEGER},",
          "Description = #{description,jdbcType=VARCHAR},",
          "Cid = #{cid,jdbcType=CHAR}",
        "where Arid = #{arid,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(TbArea record);
}