package com.guide.ssm.module.user.mapper;

import com.guide.ssm.module.user.pojo.TbArea;
import java.util.List;

public interface TbAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String arid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area
     *
     * @mbggenerated
     */
    int insert(TbArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area
     *
     * @mbggenerated
     */
    TbArea selectByPrimaryKey(String arid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area
     *
     * @mbggenerated
     */
    List<TbArea> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbArea record);
}