package com.guide.ssm.module.user.mapper;

import com.guide.ssm.module.user.pojo.TbCity;
import java.util.List;

public interface TbCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated
     */
    int insert(TbCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated
     */
    TbCity selectByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated
     */
    List<TbCity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbCity record);
}