package com.guide.ssm.module.user.mapper;

import com.guide.ssm.module.user.pojo.TbCity;
import com.guide.ssm.module.user.pojo.TbCityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TbCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated
     */
    int countByExample(TbCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated
     */
    int deleteByExample(TbCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated
     */
    @Delete({
        "delete from tb_city",
        "where Cid = #{cid,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_city (Cid, City, ",
        "Pid)",
        "values (#{cid,jdbcType=CHAR}, #{city,jdbcType=VARCHAR}, ",
        "#{pid,jdbcType=CHAR})"
    })
    int insert(TbCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated
     */
    int insertSelective(TbCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated
     */
    List<TbCity> selectByExample(TbCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "Cid, City, Pid",
        "from tb_city",
        "where Cid = #{cid,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    TbCity selectByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbCity record, @Param("example") TbCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbCity record, @Param("example") TbCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated
     */
    @Update({
        "update tb_city",
        "set City = #{city,jdbcType=VARCHAR},",
          "Pid = #{pid,jdbcType=CHAR}",
        "where Cid = #{cid,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(TbCity record);
}