package com.guide.ssm.module.user.mapper;

import com.guide.ssm.module.user.pojo.TbLine;
import java.util.List;

public interface TbLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line
     *
     * @mbggenerated
     */
    int insert(TbLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line
     *
     * @mbggenerated
     */
    TbLine selectByPrimaryKey(String lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line
     *
     * @mbggenerated
     */
    List<TbLine> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_line
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbLine record);
}