package com.guide.ssm.module.user.mapper;

import com.guide.ssm.module.user.pojo.TbLocation;
import java.util.List;

public interface TbLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    int insert(TbLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    TbLocation selectByPrimaryKey(String lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    List<TbLocation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbLocation record);
}