package com.guide.ssm.module.user.mapper;

import com.guide.ssm.module.user.pojo.TbLocation;
import com.guide.ssm.module.user.pojo.TbLocationExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TbLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    int countByExample(TbLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    int deleteByExample(TbLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    @Delete({
        "delete from tb_location",
        "where Lid = #{lid,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_location (Lid, Vid, Sid, ",
        "Time)",
        "values (#{lid,jdbcType=CHAR}, #{vid,jdbcType=CHAR}, #{sid,jdbcType=CHAR}, ",
        "#{time,jdbcType=TIMESTAMP})"
    })
    int insert(TbLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    int insertSelective(TbLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    List<TbLocation> selectByExample(TbLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "Lid, Vid, Sid, Time",
        "from tb_location",
        "where Lid = #{lid,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    TbLocation selectByPrimaryKey(String lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbLocation record, @Param("example") TbLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbLocation record, @Param("example") TbLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_location
     *
     * @mbggenerated
     */
    @Update({
        "update tb_location",
        "set Vid = #{vid,jdbcType=CHAR},",
          "Sid = #{sid,jdbcType=CHAR},",
          "Time = #{time,jdbcType=TIMESTAMP}",
        "where Lid = #{lid,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(TbLocation record);
}