package com.guide.ssm.module.user.mapper;

import com.guide.ssm.module.user.pojo.TbProvince;
import com.guide.ssm.module.user.pojo.TbProvinceExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TbProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated
     */
    int countByExample(TbProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated
     */
    int deleteByExample(TbProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated
     */
    @Delete({
        "delete from tb_province",
        "where Pid = #{pid,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_province (Pid, Province)",
        "values (#{pid,jdbcType=CHAR}, #{province,jdbcType=VARCHAR})"
    })
    int insert(TbProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated
     */
    int insertSelective(TbProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated
     */
    List<TbProvince> selectByExample(TbProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "Pid, Province",
        "from tb_province",
        "where Pid = #{pid,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    TbProvince selectByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbProvince record, @Param("example") TbProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbProvince record, @Param("example") TbProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated
     */
    @Update({
        "update tb_province",
        "set Province = #{province,jdbcType=VARCHAR}",
        "where Pid = #{pid,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(TbProvince record);
}