package com.guide.ssm.module.user.mapper;

import com.guide.ssm.module.user.pojo.TbReply;
import com.guide.ssm.module.user.pojo.TbReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TbReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbggenerated
     */
    int countByExample(TbReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbggenerated
     */
    int deleteByExample(TbReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbggenerated
     */
    @Delete({
        "delete from tb_reply",
        "where Rid = #{rid,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_reply (Rid, Title, ",
        "Reply, ADid, Time, ",
        "Aid)",
        "values (#{rid,jdbcType=CHAR}, #{title,jdbcType=VARCHAR}, ",
        "#{reply,jdbcType=VARCHAR}, #{adid,jdbcType=CHAR}, #{time,jdbcType=TIMESTAMP}, ",
        "#{aid,jdbcType=CHAR})"
    })
    int insert(TbReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbggenerated
     */
    int insertSelective(TbReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbggenerated
     */
    List<TbReply> selectByExample(TbReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "Rid, Title, Reply, ADid, Time, Aid",
        "from tb_reply",
        "where Rid = #{rid,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    TbReply selectByPrimaryKey(String rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbReply record, @Param("example") TbReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbReply record, @Param("example") TbReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbggenerated
     */
    @Update({
        "update tb_reply",
        "set Title = #{title,jdbcType=VARCHAR},",
          "Reply = #{reply,jdbcType=VARCHAR},",
          "ADid = #{adid,jdbcType=CHAR},",
          "Time = #{time,jdbcType=TIMESTAMP},",
          "Aid = #{aid,jdbcType=CHAR}",
        "where Rid = #{rid,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(TbReply record);
}