package com.guide.ssm.module.user.mapper;

import com.guide.ssm.module.user.pojo.TbReply;
import java.util.List;

public interface TbReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbggenerated
     */
    int insert(TbReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbggenerated
     */
    TbReply selectByPrimaryKey(String rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbggenerated
     */
    List<TbReply> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbReply record);
}