package com.guide.ssm.module.user.mapper;

import com.guide.ssm.module.user.pojo.TbSpot;
import com.guide.ssm.module.user.pojo.TbSpotExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TbSpotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spot
     *
     * @mbggenerated
     */
    int countByExample(TbSpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spot
     *
     * @mbggenerated
     */
    int deleteByExample(TbSpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spot
     *
     * @mbggenerated
     */
    @Delete({
        "delete from tb_spot",
        "where Sid = #{sid,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spot
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_spot (Sid, Spot, ",
        "Longitude, Latitude, Radius, ",
        "Arid, Description, ",
        "Voice)",
        "values (#{sid,jdbcType=CHAR}, #{spot,jdbcType=VARCHAR}, ",
        "#{longitude,jdbcType=CHAR}, #{latitude,jdbcType=CHAR}, #{radius,jdbcType=INTEGER}, ",
        "#{arid,jdbcType=CHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{voice,jdbcType=VARCHAR})"
    })
    int insert(TbSpot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spot
     *
     * @mbggenerated
     */
    int insertSelective(TbSpot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spot
     *
     * @mbggenerated
     */
    List<TbSpot> selectByExample(TbSpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spot
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "Sid, Spot, Longitude, Latitude, Radius, Arid, Description, Voice",
        "from tb_spot",
        "where Sid = #{sid,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    TbSpot selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spot
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbSpot record, @Param("example") TbSpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spot
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbSpot record, @Param("example") TbSpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spot
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbSpot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spot
     *
     * @mbggenerated
     */
    @Update({
        "update tb_spot",
        "set Spot = #{spot,jdbcType=VARCHAR},",
          "Longitude = #{longitude,jdbcType=CHAR},",
          "Latitude = #{latitude,jdbcType=CHAR},",
          "Radius = #{radius,jdbcType=INTEGER},",
          "Arid = #{arid,jdbcType=CHAR},",
          "Description = #{description,jdbcType=VARCHAR},",
          "Voice = #{voice,jdbcType=VARCHAR}",
        "where Sid = #{sid,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(TbSpot record);
}