package com.guide.ssm.module.user.mapper;

import com.guide.ssm.module.user.pojo.TbVisitor;
import java.util.List;

public interface TbVisitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_visitor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_visitor
     *
     * @mbggenerated
     */
    int insert(TbVisitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_visitor
     *
     * @mbggenerated
     */
    TbVisitor selectByPrimaryKey(String vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_visitor
     *
     * @mbggenerated
     */
    List<TbVisitor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_visitor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbVisitor record);
}